### ISSUE TITLE
Search icon in the sidebar

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/tiny-hestia#10]
https://prnt.sc/gng0tq

**Comment by cristian-ungureanu** [comment]
@rodica-andronache , this is an issue from main theme

**Comment by rodica-andronache** [comment]
but it's fixed in the main theme

**Comment by cristian-ungureanu** [comment]
Oh, then it means the css should be generated again for child-theme and updated in tiny-hestia. I'll take care of it. Thanks!

**Comment by rodica-andronache** [comment]
@cristian-ungureanu for me it still doesn't look ok on the wporg preview https://wordpress.org/themes/tiny-hestia/ . can you check too, please?

**Comment by cristian-ungureanu** [comment]
@rodica-andronache , I think it's because of scripts version. I fixed it here https://github.com/Codeinwp/tiny-hestia/pull/13
