### ISSUE TITLE
Logo not staying after being set

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/tiny-hestia#23]
@rodica-andronache logo doesn't stay after being set:

https://share.vidyard.com/watch/Fccmr5j14p78VUc9CoG3Xy

![image](https://user-images.githubusercontent.com/10324144/35188614-3a1ccba0-fe0f-11e7-923c-2dd8d473298f.png)

**Comment by HardeepAsrani** [comment]
@UVLabs Is it happening with a plugin installed? It works for me, see here: http://xenophobic-monkey.w6.poopy.life/

**Comment by UVLabs** [comment]
@HardeepAsrani nope still happens with all plugins deactivated

**Comment by UVLabs** [comment]
The same thing seems to happen to Boxed Layout, the setting would be on but on the live site it wouldn't be the boxed layout.

**Comment by rodica-andronache** [comment]
@UVLabs it seems to not work for me either. I'll have a look and let you know

**Comment by rodica-andronache** [comment]
@UVLabs I think it should be ok, let me know :D
