### ISSUE TITLE
Post Grid widget with 1 column

### ISSUE THREAD

**Issue by Vishakha-Patel** [Codeinwp/tiny-hestia#27]
On Homepage, add a post grid widget with 1 column like this - http://prntscr.com/l241oi.
Page Layout is the default. 

On the Home page, the image of old post shows in center while for another post it shows full width - http://prntscr.com/l242lm.

Ticket: https://secure.helpscout.net/conversation/665819846/169682/?folderId=212385

@stefan-cotitosu

**Comment by stefan-cotitosu** [comment]
@Vishakha-Patel I am not able to replicate this issue. If you have more details or see other customers complaining about it, please let me know or open the issue again.

Thanks for reporting it.
